package com.telefonia.models;
// Generated 11-22-2019 08:26:25 AM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Configuracion generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "configuracion", catalog = "si_telefonia")
public class Configuracion implements java.io.Serializable {

	private Integer idConf;
	private BigDecimal tarifaFijo;
	private BigDecimal tafifaNormal;
	private BigDecimal tarifaMismaRed;
	private Double costo;

	public Configuracion() {
	}

	public Configuracion(BigDecimal tarifaFijo, BigDecimal tafifaNormal, BigDecimal tarifaMismaRed, Double costo) {
		this.tarifaFijo = tarifaFijo;
		this.tafifaNormal = tafifaNormal;
		this.tarifaMismaRed = tarifaMismaRed;
		this.costo = costo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_conf", unique = true, nullable = false)
	public Integer getIdConf() {
		return this.idConf;
	}

	public void setIdConf(Integer idConf) {
		this.idConf = idConf;
	}

	@Column(name = "tarifa_fijo", precision = 4)
	public BigDecimal getTarifaFijo() {
		return this.tarifaFijo;
	}

	public void setTarifaFijo(BigDecimal tarifaFijo) {
		this.tarifaFijo = tarifaFijo;
	}

	@Column(name = "tafifa_normal", precision = 4)
	public BigDecimal getTafifaNormal() {
		return this.tafifaNormal;
	}

	public void setTafifaNormal(BigDecimal tafifaNormal) {
		this.tafifaNormal = tafifaNormal;
	}

	@Column(name = "tarifa_misma_red", precision = 4)
	public BigDecimal getTarifaMismaRed() {
		return this.tarifaMismaRed;
	}

	public void setTarifaMismaRed(BigDecimal tarifaMismaRed) {
		this.tarifaMismaRed = tarifaMismaRed;
	}

	@Column(name = "costo", precision = 4)
	public Double getCosto() {
		return this.costo;
	}

	public void setCosto(Double costo) {
		this.costo = costo;
	}

}
