package com.telefonia.models;
// Generated 11-22-2019 08:26:25 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CtrlServ generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "ctrl_serv", catalog = "si_telefonia")
public class CtrlServ implements java.io.Serializable {

	private Integer idCtrl;
	private Descripcion descripcion;
	private int disponible;
	private int consumido;

	public CtrlServ() {
	}

	public CtrlServ(Descripcion descripcion, int disponible, int consumido) {
		this.descripcion = descripcion;
		this.disponible = disponible;
		this.consumido = consumido;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_ctrl", unique = true, nullable = false)
	public Integer getIdCtrl() {
		return this.idCtrl;
	}

	public void setIdCtrl(Integer idCtrl) {
		this.idCtrl = idCtrl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "descripcion", nullable = false)
	public Descripcion getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(Descripcion descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "disponible", nullable = false)
	public int getDisponible() {
		return this.disponible;
	}

	public void setDisponible(int disponible) {
		this.disponible = disponible;
	}

	@Column(name = "consumido", nullable = false)
	public int getConsumido() {
		return this.consumido;
	}

	public void setConsumido(int consumido) {
		this.consumido = consumido;
	}

}
