package com.telefonia.models;
// Generated 11-22-2019 08:26:25 AM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamentos generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "departamentos", catalog = "si_telefonia")
public class Departamentos implements java.io.Serializable {

	private Integer idDepto;
	private String nombreDepto;
	private List<Municipios> municipioses = new ArrayList<Municipios>();

	public Departamentos() {
	}

	public Departamentos(String nombreDepto) {
		this.nombreDepto = nombreDepto;
	}

	public Departamentos(String nombreDepto, List<Municipios> municipioses) {
		this.nombreDepto = nombreDepto;
		this.municipioses = municipioses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_depto", unique = true, nullable = false)
	public Integer getIdDepto() {
		return this.idDepto;
	}

	public void setIdDepto(Integer idDepto) {
		this.idDepto = idDepto;
	}

	@Column(name = "nombre_depto", nullable = false, length = 150)
	public String getNombreDepto() {
		return this.nombreDepto;
	}

	public void setNombreDepto(String nombreDepto) {
		this.nombreDepto = nombreDepto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamentos")
	public List<Municipios> getMunicipioses() {
		return this.municipioses;
	}

	public void setMunicipioses(List<Municipios> municipioses) {
		this.municipioses = municipioses;
	}

}
