package com.telefonia.models;
// Generated 11-22-2019 08:26:25 AM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Descripcion generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "descripcion", catalog = "si_telefonia")
public class Descripcion implements java.io.Serializable {

	private Integer idDesc;
	private Contratos contratos;
	private Servicios servicios;
	private BigDecimal costo;
	private int vigencia;
	private boolean estado;
	private List<CtrlServ> ctrlServs = new ArrayList<CtrlServ>();
	private List<ConsExtra> consExtras = new ArrayList<ConsExtra>();
	private List<Detalle> detalles = new ArrayList<Detalle>();

	public Descripcion() {
	}

	public Descripcion(Contratos contratos, Servicios servicios, int vigencia, boolean estado) {
		this.contratos = contratos;
		this.servicios = servicios;
		this.vigencia = vigencia;
		this.estado = estado;
	}

	public Descripcion(Contratos contratos, Servicios servicios, BigDecimal costo, int vigencia, boolean estado,
			List<CtrlServ> ctrlServs, List<ConsExtra> consExtras, List<Detalle> detalles) {
		this.contratos = contratos;
		this.servicios = servicios;
		this.costo = costo;
		this.vigencia = vigencia;
		this.estado = estado;
		this.ctrlServs = ctrlServs;
		this.consExtras = consExtras;
		this.detalles = detalles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_desc", unique = true, nullable = false)
	public Integer getIdDesc() {
		return this.idDesc;
	}

	public void setIdDesc(Integer idDesc) {
		this.idDesc = idDesc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contrato", nullable = false)
	public Contratos getContratos() {
		return this.contratos;
	}

	public void setContratos(Contratos contratos) {
		this.contratos = contratos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "servicio", nullable = false)
	public Servicios getServicios() {
		return this.servicios;
	}

	public void setServicios(Servicios servicios) {
		this.servicios = servicios;
	}

	@Column(name = "costo", precision = 4)
	public BigDecimal getCosto() {
		return this.costo;
	}

	public void setCosto(BigDecimal costo) {
		this.costo = costo;
	}

	@Column(name = "vigencia", nullable = false)
	public int getVigencia() {
		return this.vigencia;
	}

	public void setVigencia(int vigencia) {
		this.vigencia = vigencia;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "descripcion")
	public List<CtrlServ> getCtrlServs() {
		return this.ctrlServs;
	}

	public void setCtrlServs(List<CtrlServ> ctrlServs) {
		this.ctrlServs = ctrlServs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "descripcion")
	public List<ConsExtra> getConsExtras() {
		return this.consExtras;
	}

	public void setConsExtras(List<ConsExtra> consExtras) {
		this.consExtras = consExtras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "descripcion")
	public List<Detalle> getDetalles() {
		return this.detalles;
	}

	public void setDetalles(List<Detalle> detalles) {
		this.detalles = detalles;
	}

}
