package com.telefonia.models;
// Generated 11-22-2019 08:26:25 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detalle generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "detalle", catalog = "si_telefonia")
public class Detalle implements java.io.Serializable {

	private Integer idDet;
	private Descripcion descripcion;
	private Facturas facturas;

	public Detalle() {
	}

	public Detalle(Descripcion descripcion, Facturas facturas) {
		this.descripcion = descripcion;
		this.facturas = facturas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_det", unique = true, nullable = false)
	public Integer getIdDet() {
		return this.idDet;
	}

	public void setIdDet(Integer idDet) {
		this.idDet = idDet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "descripcion", nullable = false)
	public Descripcion getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(Descripcion descripcion) {
		this.descripcion = descripcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "factura", nullable = false)
	public Facturas getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Facturas facturas) {
		this.facturas = facturas;
	}

}
