package com.telefonia.models;
// Generated 11-22-2019 08:26:25 AM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Direcciones generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "direcciones", catalog = "si_telefonia")
public class Direcciones implements java.io.Serializable {

	private Integer idDir;
	private Municipios municipios;
	private String direccion;
	private List<Personas> personases = new ArrayList<Personas>();

	public Direcciones() {
	}

	public Direcciones(Municipios municipios, String direccion) {
		this.municipios = municipios;
		this.direccion = direccion;
	}

	public Direcciones(Municipios municipios, String direccion, List<Personas> personases) {
		this.municipios = municipios;
		this.direccion = direccion;
		this.personases = personases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_dir", unique = true, nullable = false)
	public Integer getIdDir() {
		return this.idDir;
	}

	public void setIdDir(Integer idDir) {
		this.idDir = idDir;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "municipio", nullable = false)
	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	@Column(name = "direccion", nullable = false, length = 100)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direcciones")
	public List<Personas> getPersonases() {
		return this.personases;
	}

	public void setPersonases(List<Personas> personases) {
		this.personases = personases;
	}

}
