package com.telefonia.models;
// Generated 11-28-2019 02:08:04 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Facturas generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "facturas", catalog = "si_telefonia")
public class Facturas implements java.io.Serializable {

	private Integer idFac;
	private Contratos contratos;
	private Usuarios usuarios;
	private Date fechEmision;
	private Date fechLimite;
	private boolean estado;
	private List<Detalle> detalles = new ArrayList<Detalle>();

	public Facturas() {
	}

	public Facturas(Contratos contratos, Usuarios usuarios, Date fechEmision, Date fechLimite, boolean estado) {
		this.contratos = contratos;
		this.usuarios = usuarios;
		this.fechEmision = fechEmision;
		this.fechLimite = fechLimite;
		this.estado = estado;
	}

	public Facturas(Contratos contratos, Usuarios usuarios, Date fechEmision, Date fechLimite, boolean estado,
			List<Detalle> detalles) {
		this.contratos = contratos;
		this.usuarios = usuarios;
		this.fechEmision = fechEmision;
		this.fechLimite = fechLimite;
		this.estado = estado;
		this.detalles = detalles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_fac", unique = true, nullable = false)
	public Integer getIdFac() {
		return this.idFac;
	}

	public void setIdFac(Integer idFac) {
		this.idFac = idFac;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contrato", nullable = false)
	public Contratos getContratos() {
		return this.contratos;
	}

	public void setContratos(Contratos contratos) {
		this.contratos = contratos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario", nullable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fech_emision", nullable = false, length = 10)
	public Date getFechEmision() {
		return this.fechEmision;
	}

	public void setFechEmision(Date fechEmision) {
		this.fechEmision = fechEmision;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fech_limite", nullable = false, length = 10)
	public Date getFechLimite() {
		return this.fechLimite;
	}

	public void setFechLimite(Date fechLimite) {
		this.fechLimite = fechLimite;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facturas")
	public List<Detalle> getDetalles() {
		return this.detalles;
	}

	public void setDetalles(List<Detalle> detalles) {
		this.detalles = detalles;
	}
	/*
	 * HOLAAAA
	 * */
}
