package com.telefonia.models;
// Generated 11-22-2019 08:26:25 AM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Municipios generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "municipios", catalog = "si_telefonia")
public class Municipios implements java.io.Serializable {

	private Integer idMuni;
	private Departamentos departamentos;
	private String nombreMuni;
	private List<Direcciones> direccioneses = new ArrayList<Direcciones>();

	public Municipios() {
	}

	public Municipios(Departamentos departamentos, String nombreMuni) {
		this.departamentos = departamentos;
		this.nombreMuni = nombreMuni;
	}

	public Municipios(Departamentos departamentos, String nombreMuni, List<Direcciones> direccioneses) {
		this.departamentos = departamentos;
		this.nombreMuni = nombreMuni;
		this.direccioneses = direccioneses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_muni", unique = true, nullable = false)
	public Integer getIdMuni() {
		return this.idMuni;
	}

	public void setIdMuni(Integer idMuni) {
		this.idMuni = idMuni;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "departamento", nullable = false)
	public Departamentos getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Departamentos departamentos) {
		this.departamentos = departamentos;
	}

	@Column(name = "nombre_muni", nullable = false, length = 150)
	public String getNombreMuni() {
		return this.nombreMuni;
	}

	public void setNombreMuni(String nombreMuni) {
		this.nombreMuni = nombreMuni;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipios")
	public List<Direcciones> getDireccioneses() {
		return this.direccioneses;
	}

	public void setDireccioneses(List<Direcciones> direccioneses) {
		this.direccioneses = direccioneses;
	}

}
