package com.telefonia.models;
// Generated 11-22-2019 08:26:25 AM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoUsu generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "tipo_usu", catalog = "si_telefonia")
public class TipoUsu implements java.io.Serializable {

	private Integer idTpu;
	private String descripcion;
	private List<Usuarios> usuarioses = new ArrayList<Usuarios>();

	public TipoUsu() {
	}

	public TipoUsu(String descripcion, List<Usuarios> usuarioses) {
		this.descripcion = descripcion;
		this.usuarioses = usuarioses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tpu", unique = true, nullable = false)
	public Integer getIdTpu() {
		return this.idTpu;
	}

	public void setIdTpu(Integer idTpu) {
		this.idTpu = idTpu;
	}

	@Column(name = "descripcion", length = 75)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoUsu")
	public List<Usuarios> getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(List<Usuarios> usuarioses) {
		this.usuarioses = usuarioses;
	}

}
