package com.telefonia.models;
// Generated 11-22-2019 08:26:25 AM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@SuppressWarnings("serial")
@Table(name = "usuarios", catalog = "si_telefonia")
public class Usuarios implements java.io.Serializable {

	private Integer idUsu;
	private Personas personas;
	private TipoUsu tipoUsu;
	private String usuario;
	private byte[] pass;
	private boolean estado;
	private List<Facturas> facturases = new ArrayList<Facturas>();
	private List<Contratos> contratoses = new ArrayList<Contratos>();

	public Usuarios() {
	}

	public Usuarios(Personas personas, TipoUsu tipoUsu, String usuario, byte[] pass, boolean estado) {
		this.personas = personas;
		this.tipoUsu = tipoUsu;
		this.usuario = usuario;
		this.pass = pass;
		this.estado = estado;
	}

	public Usuarios(Personas personas, TipoUsu tipoUsu, String usuario, byte[] pass, boolean estado, List<Facturas> facturases,
			List<Contratos> contratoses) {
		this.personas = personas;
		this.tipoUsu = tipoUsu;
		this.usuario = usuario;
		this.pass = pass;
		this.estado = estado;
		this.facturases = facturases;
		this.contratoses = contratoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_usu", unique = true, nullable = false)
	public Integer getIdUsu() {
		return this.idUsu;
	}

	public void setIdUsu(Integer idUsu) {
		this.idUsu = idUsu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "persona", nullable = false)
	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_u", nullable = false)
	public TipoUsu getTipoUsu() {
		return this.tipoUsu;
	}

	public void setTipoUsu(TipoUsu tipoUsu) {
		this.tipoUsu = tipoUsu;
	}

	@Column(name = "usuario", nullable = false, length = 125)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "pass", nullable = false)
	public byte[] getPass() {
		return this.pass;
	}

	public void setPass(byte[] pass) {
		this.pass = pass;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public List<Facturas> getFacturases() {
		return this.facturases;
	}

	public void setFacturases(List<Facturas> facturases) {
		this.facturases = facturases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public List<Contratos> getContratoses() {
		return this.contratoses;
	}

	public void setContratoses(List<Contratos> contratoses) {
		this.contratoses = contratoses;
	}

}
